version: "3.2"
services:
    web:
      build: .
      volumes:
        - .:/instabug
        - bundler_gems:/usr/local/bundle
      ports:
        - "3000:3000"
      depends_on:
        - mysql
      command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    mysql:
        image: 'mysql:5.7'
        volumes:
            - mysqlvolume:/var/lib/mysql
        ports:
            - "3300:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=instabug

volumes:
    mysqlvolume:
    bundler_gems: