version: "3.2"
services:
    web:
      build: .
      volumes:
        - .:/instabug
        - bundler_gems:/usr/local/bundle
      ports:
        - "3000:3000"
      depends_on:
        - mysql
    mysql:
        image: 'mysql:5.7'
        volumes:
            - mysqlvolume:/var/lib/mysql
        ports:
            - "3300:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=instabug
    elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
      environment:
        - discovery.type=single-node
        - cluster.name=laradock-cluster
        - node.name=laradock-node
        - bootstrap.memory_lock=true
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        - "transport.host=localhost"
        - "bootstrap.system_call_filter=false"
      ulimits:
        memlock:
          soft: -1
          hard: -1
      ports:
        - 9200:9200
      volumes:
        - esvolume:/usr/share/elasticsearch/data

volumes:
    mysqlvolume:
    bundler_gems:
    esvolume: